🔀 :: (#13) navigation 초기 설정
team-xquare/android-mfa-example pull request #24
Opened 2023-08-10 05:24 UTC by JunJaBoy

2023-08-10 11:11 UTC, Tmdhoon2 requested changes

2023-08-10 11:11 UTC, Tmdhoon2 commented on app/src/main/kotlin/com/xquare/androidv2/RootActivity.kt
> +            view.updateLayoutParams<MarginLayoutParams> {
여기 insets 스코프 함수로 감싸는건 어떤가요??

2023-08-10 11:11 UTC, Tmdhoon2 commented on app/src/main/kotlin/com/xquare/androidv2/fragment/services/MainFragment.kt
> +    private var _binding: FragmentServicesMainBinding? = null
저희 https://github.com/androidbroadcast/ViewBindingPropertyDelegate 요 라이브러리 도입해보는 건 어떨까요??

매번 binding 해제해줄 필요도 없고, onDestroyView(), _binding 등의 보일러 플레이트 코드가 줄어들 수 있을 것 같아요

2023-08-10 11:11 UTC, Tmdhoon2 commented on app/src/main/kotlin/com/xquare/androidv2/fragment/services/MainFragment.kt
> +    private var _binding: FragmentServicesMainBinding? = null
+ 개인적인 생각입니당

2023-08-10 11:44 UTC, JunJaBoy commented on app/src/main/kotlin/com/xquare/androidv2/RootActivity.kt
> +            view.updateLayoutParams<MarginLayoutParams> {
넵 좋습니다! 그런데 밑에서 사용하는 insets.. 변수 접근하는 코액티비티 클래스 멤버와 구분되도록 유지하는게 좋을 것 같아요.

2023-08-10 11:48 UTC, JunJaBoy commented on app/src/main/kotlin/com/xquare/androidv2/fragment/services/MainFragment.kt
> +    private var _binding: FragmentServicesMainBinding? = null
프래그먼트 바인딩 선언할 때 Delegate 패턴으로 메모리 누수 방지해보려고 했는데, 구현이 너무 복잡해져서 #14 이슈에서 Delegate 패턴으로 처리하려고 했습니다. (승훈님께서 링크하신 라이브러리와 동일하게 동작하도록 구현하려고 했습니다)

2023-08-10 11:49 UTC, JunJaBoy reviewed
커멘트 확인했습니다

2023-08-10 12:06 UTC, Tmdhoon2 commented on app/src/main/kotlin/com/xquare/androidv2/fragment/services/MainFragment.kt
> +    private var _binding: FragmentServicesMainBinding? = null
아하 확인했습니다

2023-08-10 14:34 UTC, chlgkdms approved these changes

2023-08-12 06:02 UTC, Tmdhoon2 requested changes

2023-08-12 06:02 UTC, Tmdhoon2 commented on app/src/main/res/drawable/selector_bottom_navigation_ic_all_services.xml
> +    <item android:drawable="@drawable/ic_filled_dashboard" android:state_checked="true" />
혹시 이 아이콘들 디자인 시스템에 추가해놓은 아이콘들일까요??

2023-08-12 06:02 UTC, Tmdhoon2 commented on core/core-ui/src/main/kotlin/com/xquare/core/ui/util/WindowInsetsUtils.kt
> +fun measureSystemNavigationBarHeight(context: Context): Int =
요 함수들은 이 파일 내부에서만 사용하는 것 같은데 접근제한자 붙여도 괜찮지 않을까요??

2023-08-12 06:02 UTC, Tmdhoon2 commented on app/src/main/res/layout/activity_root.xml
> +        android:layout_width="match_parent"
혹시 이 include layout에는 사이즈 지정이 필요한가요??

2023-08-12 06:02 UTC, Tmdhoon2 commented on app/src/main/res/values-v23/themes.xml
> +        <item name="android:windowLightNavigationBar" tools:targetApi="o_mr1">true</item>
이 속성은 sdk level 23일 때도 동작하나요??

2023-08-12 06:02 UTC, Tmdhoon2 commented on core/core-datastore/src/main/kotlin/com/xquare/core/datastore/datasource/UserPreferencesDataSourceImpl.kt
> +	companion object {
개인적인 생각인데 companion object는 클래스 최상단에 선언하는게 코드 볼 때 착오가 없을 것 같아요!

2023-08-12 06:02 UTC, Tmdhoon2 commented on app/src/main/res/layout/fragment_services_main.xml
> +        android:layout_width="0dp"
여기도 마찬가지로 크기 지정이 필요한가요??

2023-08-13 06:45 UTC, JunJaBoy commented on core/core-ui/src/main/kotlin/com/xquare/core/ui/util/WindowInsetsUtils.kt
> +fun measureSystemNavigationBarHeight(context: Context): Int =
처음 코드를 작성할 때, navigation 라이브러리 내부에서 확장함수를 래핑하는 코드를 참고하여 작업해서 이렇게 작업하였어요. 이제 와서 보니 불필요하다고 느껴져서 지우도록 하겠습니다.

2023-08-13 06:47 UTC, JunJaBoy commented on app/src/main/res/layout/activity_root.xml
> +        android:layout_width="match_parent"
넵 필요합니다. 저는 include 태그 자체가 공간을 차지할 수 있는 뷰와 동일한 개념으로 이해하고 있는데, 다음 두 개의 차이점을 한 번 찾아보시면 도움될 것 같습니다.
1. include 태그 자체에 크기 속성 지정
2. include layout 내부에 크기 속성 지정

2023-08-13 06:49 UTC, JunJaBoy commented on app/src/main/res/values-v23/themes.xml
> +        <item name="android:windowLightNavigationBar" tools:targetApi="o_mr1">true</item>
tools 네임스페이스 안의 속성이어서 자세하게는 모르겠지만, 안드로이드 8.1 이후에서 지원하는 것 같습니다. 이 부분은 안드로이드 6.0 호환 관련한 이슈(#17)에 고려할 사항으로 남겨두겠습니다.

2023-08-13 06:53 UTC, JunJaBoy commented on app/src/main/res/values-v23/themes.xml
> +        <item name="android:windowLightNavigationBar" tools:targetApi="o_mr1">true</item>
\+ 안드로이드 8까지는 라이트/다크 테마가 존재하지 않아서, 테마별 system bar 컬러를 지정해줄 수 없는 걸로 기억하고 있습니다.
 여기 적힌 버전 이하에서는 (추측하기로는 런타임 오류 없이) 시스템의 기본 네비게이션 색상을 따라갈 것 같습니다.

<img width="283" alt="image" src="https://github.com/team-xquare/xquare-android-v2/assets/101160207/59b0d669-7554-4844-86c5-a0b190c49db3">

2023-08-13 07:04 UTC, JunJaBoy commented on core/core-datastore/src/main/kotlin/com/xquare/core/datastore/datasource/UserPreferencesDataSourceImpl.kt
> +	companion object {
사실 크게 상관없을 것 같은데, 처음 클래스에 접근했을 때 상수보다는 생성자, 메서드 등 클래스의 주요 기능들이 나타나면 좋을 것 같다고 생각하고 있어서 항상 companion object는 클래스 최하단에 배치합니다. 인텔리센스에서 제공하는 클래스 API들에서도 지장 없으니 딱히 수정하지는 않도록 하겠습니다만, 혹시 어느 부분에서 착오가 생기는지 말씀해주시면 코드 위치 조정 고려해볼게요

2023-08-13 07:05 UTC, JunJaBoy commented on app/src/main/res/layout/fragment_services_main.xml
> +        android:layout_width="0dp"
위 커멘트 확인 부탁드립니다

2023-08-13 07:40 UTC, yeon0821 approved these changes

2023-08-13 07:42 UTC, chlgkdms approved these changes

2023-08-13 08:44 UTC, Tmdhoon2 approved these changes

2023-08-13 09:23 UTC, merged